/**
 * FROZEN REFERENCE - the PRE-Phase-3G-F Bilibili grouping implementation.
 *
 * Extracted VERBATIM from the production bundle
 *   converted_output/assets/index.js
 * as shipped at commit 5b1ebdd (the Phase 3G-E baseline), before the false-split
 * remediation replaced it with apps/web/src/domain/bilibiliGrouping.ts.
 *
 * It is kept in-tree because the live bundle no longer contains this code, and the
 * before/after benchmark (pipeline/audit/bilibili_grouping_remediation_eval.js)
 * still needs to evaluate the OLD algorithm on the FROZEN corpus.
 *
 * Do NOT edit this file to "improve" the old algorithm, and do NOT use it at
 * runtime - it exists only so the regression comparison stays reproducible.
 */
// Auto-extracted verbatim from converted_output/assets/index.js (production bundle).
// Do not edit by hand - regenerate with pipeline/audit/bili_grouping_benchmark.py
const BILI_GENRE_BUZZWORDS = /(?:rpg|冒险|高度定制|史诗战斗|魔法|枪械|科技|生存|剧情|硬核|沉浸式|高难|爽游|原版|魔改|养老|纯净|探索|空岛|地牢|格斗|战斗|拔刀剑|工业|建造|现代战争)/gi;
const BILI_GENERIC_PACK_KEYS2 = new Set([
    "",
    "mc",
    "我的世界",
    "minecraft",
    "模组",
    "整合",
    "游戏",
    "自制",
    "包",
    "整合包",
    "全新",
    "纯净",
    "高配",
    "低配",
    "生存",
    "冒险",
    "科技",
    "魔法",
    "空岛",
    "大型",
    "超好玩",
    "免费",
    "客户端",
    "体验"
  ]);
function cleanPackKey(s) {
  if (!s) return "";
  let str = String(s);
  str = str.replace(/[\uD835][\uDC00-\uDFFF]/g, "");
  str = str.replace(/(?:我的世界|minecraft|mine\s*craft|mc)/gi, " ");
  str = str.replace(/[【】[\]（）(){}\u300C\u300D\u300E\u300F《》/|·~～!！?？:：\-—+*#]+/g, " ");
  str = str.replace(/(?:mc|minecraft|我的世界)?\s*1\.\d{1,2}(?:\.\d+)?/gi, " ");
  str = str.replace(/(?:v|ver|version)?\s*\d+(?:\.\d+)+(?:[a-z\d_\-.]*)?/gi, " ");
  str = str.replace(/(?:v|ver|version)\s*\d+/gi, " ");
  str = str.replace(/\b(?:forge|fabric|neoforge|quilt)\b/gi, " ");
  str = str.replace(/(?:整合包|模组包|魔改包|懒人包|重制版|正式版|抢先版|公测版|抢先体验|测试版)/g, " ");
  str = str.replace(/(?:最新|首发|公测|更新|发布|分享|下载|自制|自创|开坑|入坑|通关|介绍|演示|实况|推荐)/g, " ");
  str = str.replace(BILI_GENRE_BUZZWORDS, " ");
  str = str.replace(/(?:新的征途.*|从此刻开始.*|第一期.*|第二期.*|第\d+期.*|ep\d+.*)/gi, " ");
  str = str.replace(/[^\u4e00-\u9fa5a-zA-Z0-9]/g, " ").trim().toLowerCase();
  str = str.replace(/\s+/g, " ");
  return str;
}
function groupPacks(packs) {
    var map = {};
    var groups = [];
    window.biliGroupsMap = map;
    packs.forEach(function(p) {
      var rawKey = cleanPackKey(p.title);
      var authorKey = (p.author || "unknown").trim().toLowerCase();
      var key = "";
      if (!rawKey || rawKey.length <= 3 || BILI_GENERIC_PACK_KEYS2.has(rawKey)) {
        key = "__raw_" + p.bvid;
      } else {
        var matchedExistingKey = null;
        for (var k in map) {
          if (k.indexOf(authorKey + "::") === 0) {
            var existRaw = k.substring(authorKey.length + 2);
            if (existRaw === rawKey || existRaw.length >= 4 && rawKey.indexOf(existRaw) !== -1 || rawKey.length >= 4 && existRaw.indexOf(rawKey) !== -1) {
              matchedExistingKey = k;
              break;
            }
          }
        }
        if (matchedExistingKey) {
          key = matchedExistingKey;
        } else {
          key = authorKey + "::" + rawKey;
        }
      }
      if (!map[key]) {
        map[key] = {
          key,
          displayTitle: p.title,
          author: p.author,
          pic: p.pic,
          latestTimestamp: p.pub_timestamp || 0,
          latestPubTime: p.pub_time || "",
          items: [],
          allVersions: /* @__PURE__ */ new Set(),
          allLoaders: /* @__PURE__ */ new Set(),
          allCategories: /* @__PURE__ */ new Set(),
          allLinks: [],
          allGroups: /* @__PURE__ */ new Set(),
          totalViews: 0,
          totalLikes: 0,
          totalCoins: 0,
          totalFavs: 0,
          totalShare: 0,
          totalReply: 0,
          totalDanmaku: 0,
          has_server: false,
          has_group_version: false,
          group_version_note: "",
          pack_version: "",
          desc_updated_at: ""
        };
        groups.push(map[key]);
      }
      var g = map[key];
      g.items.push(p);
      if ((p.pub_timestamp || 0) > g.latestTimestamp) {
        g.latestTimestamp = p.pub_timestamp || 0;
        g.latestPubTime = p.pub_time || "";
        g.displayTitle = p.title;
        g.pic = p.pic;
      }
      if (p.has_server) g.has_server = true;
      if (p.has_group_version) g.has_group_version = true;
      if (p.pack_version && !g.pack_version) g.pack_version = p.pack_version;
      if (p.group_version_note && !g.group_version_note) g.group_version_note = p.group_version_note;
      if (p.desc_updated_at && !g.desc_updated_at) g.desc_updated_at = p.desc_updated_at;
      if (p.mc_version && p.mc_version !== "未知") g.allVersions.add(p.mc_version);
      if (p.all_versions && Array.isArray(p.all_versions)) {
        p.all_versions.forEach(function(v) {
          if (v && v !== "未知") g.allVersions.add(v);
        });
      }
      if (p.loaders && Array.isArray(p.loaders)) {
        p.loaders.forEach(function(l) {
          g.allLoaders.add(l);
        });
      }
      if (p.categories && Array.isArray(p.categories)) {
        p.categories.forEach(function(c) {
          g.allCategories.add(c);
        });
      }
      if (p.download_links && Array.isArray(p.download_links)) {
        p.download_links.forEach(function(l) {
          g.allLinks.push(l);
        });
      }
      if (p.qq_group) g.allGroups.add(p.qq_group);
      g.totalViews += p.views || 0;
      g.totalLikes += p.likes || 0;
      g.totalCoins += p.coins || 0;
      g.totalFavs += p.favorites || 0;
      g.totalShare += p.share || 0;
      g.totalReply += p.reply || 0;
      g.totalDanmaku += p.danmaku || 0;
    });
    groups.forEach(function(g) {
      g.items.sort(function(a, b) {
        return (b.pub_timestamp || 0) - (a.pub_timestamp || 0);
      });
      var clean = cleanPackKey(g.displayTitle);
      if (clean.length >= 2) {
        var words = clean.split(" ");
        g.cleanDisplayName = words.slice(0, 3).join(" ").toUpperCase();
      } else {
        g.cleanDisplayName = g.displayTitle;
      }
    });
    return groups;
  }
module.exports = { cleanPackKey, groupPacks, BILI_GENERIC_PACK_KEYS2, BILI_GENRE_BUZZWORDS };
